### ISSUE TITLE
Passwords don't seem to be encrypted

### ISSUE THREAD

**Issue by CleanMachine1** [GabeCoder/password-manager#1]
Its a big issue to store passwords' standard in a folder called .passwords

You may want to consider using gpg to encrypt and decrypt the passwords

Also sorry to mention but there are password-managers everywhere

https://wiki.archlinux.org/index.php/GNOME/Keyring

**Comment by CleanMachine1** [comment]
Ignore, didn't see the issue at pi-apps

**Comment by GabeCoder** [comment]
> Its a big issue to store passwords' standard in a folder called .passwords
> 
> You may want to consider using gpg to encrypt and decrypt the passwords
> 
> Also sorry to mention but there are password-managers everywhere
> 
> https://wiki.archlinux.org/index.php/GNOME/Keyring

Yeah, I only made this for fun.

**Comment by CleanMachine1** [comment]
Yeah, sorry to be downer, just projects like password security should be secure products

Good code overall

**Comment by CleanMachine1** [comment]
Yeah, sorry to be downer, just projects like password security should be secure products

Good code overall

**Comment by GabeCoder** [comment]
> Yeah, sorry to be downer, just projects like password security should be secure products
> 
> Good code overall

There are better password managers like 1Password anyway. Plus, there’s no authentication.
It’s just menu and BOOM! Somebody leaked your password.
